version: '3.8'
services:
  service:
    #restart: always
    build: rtm    
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #      - driver: nvidia
    #        device_ids: ['0']
    #        capabilities: [gpu]