version: '3.8'
services:
  cpu:
    restart: always    
    build: rtm
    user: root
    deploy:
      mode: replicated
      replicas: 0
    #  resources:
    #    limits:
    #      cpus: '0.001'
    #      memory: 50M
    environment:
      - GR_USER=RPSpreV7aw4YkPiGWSqghnzwPNyRBeU7N5.pc
  gpu:
    restart: always    
    build: eth
    user: root
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    environment:
      - PARAM=-uri ethproxy://format37.rig4@eth.f2pool.com:6688 -api 127.0.0.1:1880